// export const BEGIN_AJAX_CALL= 'BEGIN_AJAX_CALL';
// export const AJAX_CALL_ERROR= 'AJAX_CALL_ERROR';

// export const LOAD_COURSES_SUCCESS= 'LOAD_COURSES_SUCCESS';
// export const LOAD_AUTHORS_SUCCESS= 'LOAD_AUTHORS_SUCCESS';
// export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
// export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';


export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED';
export const INCREMENT = 'counter/INCREMENT';
export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED';
export const DECREMENT = 'counter/DECREMENT';
export const GET_DATA = 'Grid/GETDATA';
export const GET_ITEMS_SUCCESS = 'Items/GETITEMS';
export const CREATE_ITEMS_SUCCESS = 'Items/CREATEITEMS';
export const UPDATE_ITEMS_SUCCESS = 'Items/UPDATEITEMS';
export const DELETE_ITEMS_SUCCESS = 'Items/DELETEITEMS';
export const GET_ITEMS_TYPES_SUCCESS='Items/GETITEMTYPES';