export const GET_DATA = 'Grid/GETDATA';
export const GET_ITEMS_SUCCESS = 'Items/GETITEMS';
export const CREATE_ITEMS_SUCCESS = 'Items/CREATEITEMS';
export const UPDATE_ITEMS_SUCCESS = 'Items/UPDATEITEMS';
export const DELETE_ITEMS_SUCCESS = 'Items/DELETEITEMS';
export const GET_ITEMS_TYPES_SUCCESS='Items/GETITEMTYPES';